"use client";
import { useState } from "react";
import { Field, FormActions, Modal } from "./form-primitives";

export function RentalControls({id}:{id:string}){
  const[ending,setEnding]=useState(false);const[reason,setReason]=useState("");const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);
  async function act(action:"EXTEND"|"END") {if(action==="END"&&!reason.trim()){setMessage("A reason is required.");return;}setSaving(true);const r=await fetch(`/api/admin/rentals/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(action==="EXTEND"?{action,weeks:1}:{action,reason})});const body=await r.json().catch(()=>({}));if(r.ok)location.reload();else{setMessage(body.error??"Rental update failed.");setSaving(false)}}
  return <div className="inline-action"><button className="button btn btn-outline-light secondary" type="button" disabled={saving} onClick={()=>void act("EXTEND")}>Extend one week</button><button className="button btn btn-danger danger" type="button" onClick={()=>setEnding(true)}>End rental</button><Modal open={ending} onClose={()=>setEnding(false)} title="End rental" description="Ending is immediate and should only be used after confirming the operational handoff." closeOnBackdrop={!saving}><div className="modern-form"><Field label="Reason for ending"><textarea className="form-control" autoFocus value={reason} onChange={e=>setReason(e.target.value)} required/></Field>{message&&<p className="form-message" role="alert">{message}</p>}<FormActions><button className="button btn btn-outline-light secondary" type="button" onClick={()=>setEnding(false)}>Keep active</button><button className="button btn btn-danger danger" type="button" disabled={saving} onClick={()=>void act("END")}>{saving?"Ending…":"Confirm end rental"}</button></FormActions></div></Modal></div>;
}
export function ActivateInvoice({id}:{id:string}){const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);async function activate(){setSaving(true);const r=await fetch("/api/admin/rentals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invoiceId:id,weeks:1})});const body=await r.json().catch(()=>({}));if(r.ok)location.reload();else{setMessage(body.error??"Activation failed: inventory may be occupied.");setSaving(false)}}return <div><button className="button btn btn-primary" type="button" disabled={saving} onClick={()=>void activate()}>{saving?"Activating…":"Activate lease"}</button>{message&&<span role="alert">{message}</span>}</div>}
