ALTER TABLE pricing ADD COLUMN IF NOT EXISTS stripe_setup_minor int NOT NULL DEFAULT 0 CHECK(stripe_setup_minor>=0);
ALTER TABLE bot_outbox ADD COLUMN IF NOT EXISTS challenge_id uuid REFERENCES login_challenges(id) ON DELETE CASCADE;
ALTER TABLE bot_outbox ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE bot_outbox ADD COLUMN IF NOT EXISTS dead_lettered_at timestamptz;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS expected_amount_linden int;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS expected_amount_minor int;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS expected_currency char(3);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS reconciliation_note text;
ALTER TABLE stripe_events ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE stripe_events ADD COLUMN IF NOT EXISTS processing_status text;
ALTER TABLE stripe_events ADD COLUMN IF NOT EXISTS processing_note text;
UPDATE stripe_events SET event_type=COALESCE(event_type,'legacy'),processing_status=COALESCE(processing_status,'PROCESSED');
ALTER TABLE stripe_events ALTER COLUMN event_type SET NOT NULL;
ALTER TABLE stripe_events ALTER COLUMN processing_status SET NOT NULL;
ALTER TABLE terminal_payment_events ADD COLUMN IF NOT EXISTS expected_amount_linden int;
UPDATE terminal_payment_events SET expected_amount_linden=amount_linden WHERE expected_amount_linden IS NULL;
ALTER TABLE terminal_payment_events ALTER COLUMN expected_amount_linden SET NOT NULL;
ALTER TABLE terminal_payment_events ADD COLUMN IF NOT EXISTS resolution_note text;
ALTER TABLE terminal_payment_events ADD COLUMN IF NOT EXISTS resolved_by uuid REFERENCES users(id);
ALTER TABLE terminal_payment_events ADD COLUMN IF NOT EXISTS resolved_at timestamptz;
CREATE UNIQUE INDEX IF NOT EXISTS one_active_pricing ON pricing(listing_id) WHERE active;
CREATE INDEX IF NOT EXISTS terminal_nonce_retention ON terminal_nonces(seen_at);
CREATE INDEX IF NOT EXISTS terminal_outbound_retention ON terminal_outbound_events(created_at);
CREATE TABLE IF NOT EXISTS stripe_checkout_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_id uuid NOT NULL REFERENCES invoices(id), generation int NOT NULL DEFAULT 1, idempotency_key text NOT NULL UNIQUE, session_id text UNIQUE, session_url text, status text NOT NULL CHECK(status IN ('CREATING','OPEN','COMPLETED','EXPIRED','FAILED')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(invoice_id,generation));
CREATE TABLE IF NOT EXISTS bot_health (worker_id text PRIMARY KEY, mode text NOT NULL, adapter_connected boolean NOT NULL, last_db_ok_at timestamptz NOT NULL, heartbeat_at timestamptz NOT NULL, last_error text);
DO $$ BEGIN ALTER TABLE payments ADD CONSTRAINT payment_provider_amount_shape CHECK((provider='LINDEN' AND amount_linden IS NOT NULL AND amount_minor IS NULL) OR (provider IN ('STRIPE','SIMULATION') AND amount_minor IS NOT NULL AND amount_linden IS NULL)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
