import {Bot,BotOptionFlags,LoginParameters,UUID} from "@caspertech/node-metaverse";
export interface MessageAdapter{connect():Promise<void>;resolveAvatar(username:string):Promise<{avatarId:string;displayName:string}|null>;sendInstantMessage(avatarId:string,message:string):Promise<void>;close():Promise<void>;isConnected():boolean}
export function retryDelaySeconds(attempts:number):number{return Math.min(300,2**(attempts+1))}
export function withTimeout<T>(work:Promise<T>,ms:number,message="adapter timeout"):Promise<T>{return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(message)),ms);work.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})})}
export class SimulationAdapter implements MessageAdapter{private connected=false;constructor(private readonly deliver:(avatarId:string,message:string)=>Promise<void>){}async connect(){this.connected=true}async resolveAvatar(){return null}async sendInstantMessage(avatarId:string,message:string){if(!this.connected)throw new Error("adapter disconnected");await this.deliver(avatarId,message)}async close(){this.connected=false}isConnected(){return this.connected}}
export class NodeMetaverseAdapter implements MessageAdapter{
 private bot?:Bot;private connected=false;private disconnectSubscription?:{unsubscribe():void};constructor(private readonly username:string,private readonly password:string,private readonly connectTimeoutMs=15_000){}
 async connect(){await this.close().catch(()=>undefined);const parts=this.username.trim().split(/\s+/);const login=new LoginParameters();login.firstName=parts[0]??"";login.lastName=parts.slice(1).join(" ")||"Resident";login.password=this.password;login.start="last";const candidate=new Bot(login,BotOptionFlags.LiteObjectStore|BotOptionFlags.StoreMyAttachmentsOnly);this.bot=candidate;this.disconnectSubscription=candidate.clientEvents.onDisconnected.subscribe(()=>{if(this.bot===candidate)this.connected=false});try{await withTimeout(candidate.login(),this.connectTimeoutMs,"SL login timeout");await withTimeout(candidate.connectToSim(),this.connectTimeoutMs,"SL simulator connect timeout");if(this.bot!==candidate)throw new Error("SL connection superseded");this.connected=true}catch(error){this.connected=false;if(this.bot===candidate)this.bot=undefined;this.disconnectSubscription?.unsubscribe();this.disconnectSubscription=undefined;await candidate.close().catch(()=>undefined);throw error}}
 async resolveAvatar(username:string){if(!this.bot||!this.connected)throw new Error("bot not connected");try{const found=await withTimeout(this.bot.clientCommands.grid.avatarName2KeyAndName(username),10_000,"SL name lookup timeout");return{avatarId:found.avatarKey.toString(),displayName:found.avatarName}}catch{return null}}
 async sendInstantMessage(avatarId:string,message:string){if(!this.bot||!this.connected)throw new Error("bot not connected");try{await this.bot.clientCommands.comms.sendInstantMessage(new UUID(avatarId),message)}catch(error){this.connected=false;throw error}}
 async close(){this.connected=false;this.disconnectSubscription?.unsubscribe();this.disconnectSubscription=undefined;const bot=this.bot;this.bot=undefined;if(bot)await withTimeout(bot.close(),5_000,"SL close timeout")}
 isConnected(){return this.connected}
}
