import { openMessage, validateBotRuntimeConfig } from "@lake-tech/core";
import { closePool, pool, transaction } from "@lake-tech/db";
import { NodeMetaverseAdapter, retryDelaySeconds, SimulationAdapter, type MessageAdapter } from "./adapters.js";
const cfg=validateBotRuntimeConfig(process.env);let stopping=false;const db=pool();const workerId="sl-bot";
const adapter:MessageAdapter=cfg.simulation?new SimulationAdapter(async(avatarId,message)=>{await db.query("INSERT INTO simulation_mailbox(avatar_id,message) VALUES($1,$2)",[avatarId,message])}):new NodeMetaverseAdapter(cfg.botUsername!,cfg.botPassword!);
const timeout=<T>(work:Promise<T>,ms=10_000)=>Promise.race([work,new Promise<T>((_,reject)=>setTimeout(()=>reject(new Error("adapter send timeout")),ms))]);
async function health(error:string|null=null){await db.query(`INSERT INTO bot_health(worker_id,mode,adapter_connected,last_db_ok_at,heartbeat_at,last_error) VALUES($1,$2,$3,now(),now(),$4) ON CONFLICT(worker_id) DO UPDATE SET adapter_connected=$3,last_db_ok_at=now(),heartbeat_at=now(),last_error=$4`,[workerId,cfg.simulation?"simulation":"real",adapter.isConnected(),error]);}
async function connectWithBackoff(){let attempt=0;while(!stopping&&!adapter.isConnected()){try{await adapter.connect();await health();return}catch(error){attempt++;await health(error instanceof Error?error.message:"connect failed").catch(()=>undefined);await new Promise(r=>setTimeout(r,retryDelaySeconds(attempt)*1000));}}}
type Item={id:string;avatar_id:string|null;target_username:string|null;payload:{sealed:string};attempts:number;challenge_id:string|null;expires_at:Date|null};
async function claim():Promise<Item|null>{return transaction(async client=>{const row=await client.query<Item>(`SELECT o.id,o.avatar_id,o.target_username,o.payload,o.attempts,o.challenge_id,o.expires_at FROM bot_outbox o LEFT JOIN login_challenges c ON c.id=o.challenge_id WHERE o.sent_at IS NULL AND o.dead_lettered_at IS NULL AND o.available_at<=now() AND (o.claimed_at IS NULL OR o.claimed_at<now()-interval '2 minutes') ORDER BY o.created_at FOR UPDATE OF o SKIP LOCKED LIMIT 1`);const item=row.rows[0];if(!item)return null;if(item.attempts>=8||item.expires_at&&item.expires_at<=new Date()){await client.query("UPDATE bot_outbox SET dead_lettered_at=now(),claimed_at=NULL,last_error='expired or attempts exhausted' WHERE id=$1",[item.id]);return null;}if(item.challenge_id){const valid=await client.query("SELECT 1 FROM login_challenges WHERE id=$1 AND consumed_at IS NULL AND expires_at>now()",[item.challenge_id]);if(!valid.rowCount){await client.query("UPDATE bot_outbox SET dead_lettered_at=now(),last_error='challenge no longer deliverable' WHERE id=$1",[item.id]);return null;}}await client.query("UPDATE bot_outbox SET claimed_at=now(),attempts=attempts+1 WHERE id=$1",[item.id]);return item;});}
async function processOne(){const item=await claim();if(!item)return false;try{if(!adapter.isConnected())await connectWithBackoff();let avatarId=item.avatar_id;if(!avatarId){if(!item.target_username)throw new Error("delivery target missing");const resolved=await timeout(adapter.resolveAvatar(item.target_username));if(!resolved)throw new Error("Second Life account not found");avatarId=resolved.avatarId;await transaction(async client=>{if(item.challenge_id){const challenge=await client.query("UPDATE login_challenges SET avatar_id=$2 WHERE id=$1 AND consumed_at IS NULL AND expires_at>now() RETURNING id",[item.challenge_id,avatarId]);if(challenge.rowCount!==1)throw new Error("challenge no longer deliverable");}await client.query("UPDATE bot_outbox SET avatar_id=$2 WHERE id=$1 AND sent_at IS NULL",[item.id,avatarId]);});}const message=openMessage(item.payload.sealed,cfg.otpSecret);await timeout(adapter.sendInstantMessage(avatarId,message));await transaction(client=>client.query("UPDATE bot_outbox SET sent_at=now(),claimed_at=NULL,payload=jsonb_build_object('delivered',true) WHERE id=$1 AND sent_at IS NULL",[item.id]));await health();}catch(error){const message=error instanceof Error?error.message:"delivery failed";await transaction(client=>client.query(`UPDATE bot_outbox SET claimed_at=NULL,available_at=now()+($2||' seconds')::interval,last_error=$3,dead_lettered_at=CASE WHEN attempts>=8 OR expires_at<=now() THEN now() ELSE dead_lettered_at END WHERE id=$1 AND sent_at IS NULL`,[item.id,String(retryDelaySeconds(item.attempts)),message]));await health(message).catch(()=>undefined);}return true;}
async function loop(){await connectWithBackoff();while(!stopping){try{const worked=await processOne();if(!worked)await new Promise(r=>setTimeout(r,1000));await health();}catch(error){await health(error instanceof Error?error.message:"worker failure").catch(()=>undefined);await new Promise(r=>setTimeout(r,2000));}}}
async function shutdown(){if(stopping)return;stopping=true;await adapter.close();await db.query("DELETE FROM bot_health WHERE worker_id=$1",[workerId]).catch(()=>undefined);await closePool();console.log("SL bot stopped")}
process.on("SIGTERM",()=>void shutdown());process.on("SIGINT",()=>void shutdown());console.log(`SL bot worker ready (${cfg.simulation?"simulation":"real"})`);await loop();
