export type ProviderAction={id:string;payment_id:string;provider_reference:string;amount_minor:number;idempotency_key:string;attempts:number};
export type Queryable={query<T extends Record<string,unknown>=Record<string,unknown>>(sql:string,values?:unknown[]):Promise<{rows:T[];rowCount:number|null}>};
export type Transaction=<T>(fn:(db:Queryable)=>Promise<T>)=>Promise<T>;
export type RefundProvider=(input:{paymentIntent:string;amountMinor:number;idempotencyKey:string})=>Promise<{id:string;status:string}>;

export async function claimProviderAction(db:Queryable):Promise<ProviderAction|null>{
 const found=await db.query<ProviderAction>(`SELECT id,payment_id,provider_reference,amount_minor,idempotency_key,attempts FROM provider_actions WHERE ((state IN ('QUEUED','FAILED') AND available_at<=now()) OR (state='PROCESSING' AND lease_expires_at<=now())) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`);const action=found.rows[0];if(!action)return null;
 if(action.attempts>=12){await db.query("UPDATE provider_actions SET state='MANUAL_REVIEW',last_error='attempts exhausted',lease_expires_at=NULL,updated_at=now() WHERE id=$1",[action.id]);return null;}
 const changed=await db.query("UPDATE provider_actions SET state='PROCESSING',attempts=attempts+1,lease_expires_at=now()+interval '2 minutes',last_error=NULL,updated_at=now() WHERE id=$1 AND (state IN ('QUEUED','FAILED') OR (state='PROCESSING' AND lease_expires_at<=now()))",[action.id]);if(changed.rowCount!==1)return null;return action;
}
async function complete(db:Queryable,action:ProviderAction,refund:{id:string;status:string}){const locked=await db.query<{state:string}>("SELECT state FROM provider_actions WHERE id=$1 FOR UPDATE",[action.id]);if(locked.rows[0]?.state!=="PROCESSING")throw new Error("provider action claim lost");const succeeded=refund.status==="succeeded";const changed=await db.query(`UPDATE provider_actions SET state=$2,provider_action_id=$3,provider_status=$4,lease_expires_at=NULL,available_at=CASE WHEN $2='QUEUED' THEN now()+interval '1 minute' ELSE available_at END,updated_at=now() WHERE id=$1 AND state='PROCESSING'`,[action.id,succeeded?"SUCCEEDED":"QUEUED",refund.id,refund.status]);if(changed.rowCount!==1)throw new Error("provider action completion conflict");await db.query("UPDATE payments SET status=$2,reconciliation_note=$3 WHERE id=$1",[action.payment_id,succeeded?"REFUNDED":"MANUAL_REVIEW",`Automatic Stripe refund ${refund.status}; provider refund ${refund.id}`]);}
async function fail(tx:Transaction,action:ProviderAction,error:unknown){await tx(db=>db.query(`UPDATE provider_actions SET state=CASE WHEN attempts>=12 THEN 'MANUAL_REVIEW' ELSE 'FAILED' END,lease_expires_at=NULL,available_at=now()+interval '1 minute',last_error=$2,updated_at=now() WHERE id=$1 AND state='PROCESSING'`,[action.id,error instanceof Error?error.message:"provider error"]).then(()=>undefined));}
export async function runOneProviderAction(tx:Transaction,provider:RefundProvider):Promise<boolean>{const action=await tx(claimProviderAction);if(!action)return false;try{const refund=await provider({paymentIntent:action.provider_reference,amountMinor:action.amount_minor,idempotencyKey:action.idempotency_key});await tx(db=>complete(db,action,refund));}catch(error){await fail(tx,action,error);}return true;}
