import {NextResponse} from "next/server";
import Stripe from "stripe";
import {checkoutRequestSchema} from "@lake-tech/contracts";
import {transaction} from "@lake-tech/db";
import {currentViewer} from "../../../lib/auth";
import {createCheckoutHold,createRenewalCheckoutHold,settleCheckoutInvoice} from "../../../lib/checkout";
import {checkoutSessionParameters,loadExistingCheckoutAttempt,loadExistingRenewalAttempt,type ExistingCheckoutAttempt} from "../../../lib/checkout-attempt";
import {env} from "../../../lib/env";
import {assertBrowserOrigin,noStoreHeaders} from "../../../lib/http";
import{checkoutSessionDecision,stripeCheckoutExpiresAt}from"../../../lib/stripe-checkout";
import {can} from "@lake-tech/core";

type CheckoutTarget={listingId?:string;rentalId?:string};
export async function acquireAttempt(target:CheckoutTarget,userId:string):Promise<ExistingCheckoutAttempt>{return transaction(async db=>{let listingId=target.listingId;if(target.rentalId){const found=await db.query<{listing_id:string}>("SELECT listing_id FROM rentals WHERE id=$1 AND user_id=$2",[target.rentalId,userId]);listingId=found.rows[0]?.listing_id;}if(!listingId)throw new Error("checkout target unavailable");await db.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`listing:${listingId}`]);const existing=target.rentalId?await loadExistingRenewalAttempt(db,target.rentalId,userId):await loadExistingCheckoutAttempt(db,listingId,userId);if(existing)return existing;const h=target.rentalId?await createRenewalCheckoutHold(db,target.rentalId,userId):await createCheckoutHold(db,listingId,userId);const attemptId=crypto.randomUUID(),idempotencyKey=`lte-checkout-${h.invoiceId}-1`,providerExpiresAt=stripeCheckoutExpiresAt();await db.query("INSERT INTO stripe_checkout_attempts(id,invoice_id,generation,idempotency_key,status,provider_expires_at) VALUES($1,$2,1,$3,'CREATING',$4)",[attemptId,h.invoiceId,idempotencyKey,providerExpiresAt]);const locked=await db.query<{amount_minor:number;currency:string}>("SELECT amount_minor,currency FROM invoices WHERE id=$1 FOR UPDATE",[h.invoiceId]);const invoice=locked.rows[0]!;return{invoiceId:h.invoiceId,rentalId:h.rentalId,listingId:h.listingId,name:h.name,amountMinor:invoice.amount_minor,currency:invoice.currency.trim().toLowerCase(),attemptId,idempotencyKey,sessionId:null,sessionUrl:null,providerExpiresAt,rentalStatus:target.rentalId?"ACTIVE":"PENDING"};});}
async function replaceExpired(hold:ExistingCheckoutAttempt,userId:string):Promise<ExistingCheckoutAttempt>{return transaction(async db=>{await db.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`listing:${hold.listingId}`]);const attempt=await db.query("UPDATE stripe_checkout_attempts SET status='EXPIRED',updated_at=now() WHERE id=$1 AND status IN ('CREATING','OPEN','FAILED')",[hold.attemptId]);const invoice=await db.query("UPDATE invoices SET status='VOID' WHERE id=$1 AND status='OPEN'",[hold.invoiceId]);const rental=hold.rentalStatus==="PENDING"?await db.query("UPDATE rentals SET status='CANCELLED' WHERE id=$1 AND status='PENDING'",[hold.rentalId]):{rowCount:1};if(attempt.rowCount!==1||invoice.rowCount!==1||rental.rowCount!==1)throw new Error("checkout replacement conflict");const h=hold.rentalStatus==="ACTIVE"?await createRenewalCheckoutHold(db,hold.rentalId,userId):await createCheckoutHold(db,hold.listingId,userId);const attemptId=crypto.randomUUID(),idempotencyKey=`lte-checkout-${h.invoiceId}-1`,providerExpiresAt=stripeCheckoutExpiresAt();await db.query("INSERT INTO stripe_checkout_attempts(id,invoice_id,generation,idempotency_key,status,provider_expires_at) VALUES($1,$2,1,$3,'CREATING',$4)",[attemptId,h.invoiceId,idempotencyKey,providerExpiresAt]);const locked=await db.query<{amount_minor:number;currency:string}>("SELECT amount_minor,currency FROM invoices WHERE id=$1 FOR UPDATE",[h.invoiceId]);return{invoiceId:h.invoiceId,rentalId:h.rentalId,listingId:h.listingId,name:h.name,amountMinor:locked.rows[0]!.amount_minor,currency:locked.rows[0]!.currency.trim().toLowerCase(),attemptId,idempotencyKey,sessionId:null,sessionUrl:null,providerExpiresAt,rentalStatus:hold.rentalStatus};});}
export async function POST(req:Request){const cfg=env();try{assertBrowserOrigin(req.headers,cfg.baseUrl)}catch{return NextResponse.json({error:"Invalid origin"},{status:403,headers:noStoreHeaders})}const viewer=await currentViewer();if(!viewer)return NextResponse.json({error:"Login required"},{status:401,headers:noStoreHeaders});if(!can(viewer.role,"checkout:create"))return NextResponse.json({error:"Forbidden"},{status:403,headers:noStoreHeaders});const parsed=checkoutRequestSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Checkout target required"},{status:400,headers:noStoreHeaders});const body=parsed.data;let hold:ExistingCheckoutAttempt;try{hold=await acquireAttempt(body,viewer.id)}catch{return NextResponse.json({error:"Property is unavailable"},{status:409,headers:noStoreHeaders})}
 if(cfg.simulation){await transaction(async db=>{await settleCheckoutInvoice(db,{invoiceId:hold!.invoiceId,provider:"SIMULATION",providerReference:`sim-${hold!.attemptId}`,amountMinor:hold!.amountMinor,currency:hold!.currency});const changed=await db.query("UPDATE stripe_checkout_attempts SET status='COMPLETED',updated_at=now() WHERE id=$1 AND status IN ('CREATING','FAILED')",[hold!.attemptId]);if(changed.rowCount!==1)throw new Error("checkout attempt completion conflict")});return NextResponse.json({url:`${cfg.baseUrl}/checkout/success?invoice=${hold.invoiceId}`},{headers:noStoreHeaders})}
 const stripe=new Stripe(cfg.stripeSecret!);try{if(hold.sessionId&&hold.sessionUrl){const authoritative=await stripe.checkout.sessions.retrieve(hold.sessionId);const decision=checkoutSessionDecision(authoritative);if(decision==="REUSE")return NextResponse.json({url:authoritative.url??hold.sessionUrl},{headers:noStoreHeaders});if(decision==="AWAIT_WEBHOOK")return NextResponse.json({url:`${cfg.baseUrl}/checkout/success?invoice=${hold.invoiceId}`,pendingWebhook:true},{headers:noStoreHeaders});hold=await replaceExpired(hold,viewer.id)}const session=await stripe.checkout.sessions.create(checkoutSessionParameters(hold,cfg.baseUrl),{idempotencyKey:hold.idempotencyKey});await transaction(async db=>{const changed=await db.query("UPDATE stripe_checkout_attempts SET session_id=$2,session_url=$3,status='OPEN',updated_at=now() WHERE id=$1 AND status IN ('CREATING','FAILED')",[hold!.attemptId,session.id,session.url]);if(changed.rowCount!==1)throw new Error("checkout attempt persistence conflict")});return NextResponse.json({url:session.url},{headers:noStoreHeaders})}catch(error){await transaction(db=>db.query("UPDATE stripe_checkout_attempts SET status='FAILED',updated_at=now() WHERE id=$1 AND status IN ('CREATING','FAILED')",[hold!.attemptId])).catch(()=>undefined);console.error("checkout session operation failed",error instanceof Error?error.message:"provider error");return NextResponse.json({error:"Checkout unavailable"},{status:503,headers:noStoreHeaders})}}
