import React from "react";import{renderToStaticMarkup}from"react-dom/server";import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{ListingPricingForm,ListingsManager}from"../components/inventory-form.js";import{Modal}from"../components/form-primitives.js";import{TerminalActions,TerminalProvisionForm}from"../components/admin-ops.js";import{ProviderRecoveryAction}from"../components/provider-recovery-action.js";
describe("Control Room management controls",()=>{
 it("renders decimal currency pricing editors with accessible labels",()=>{const html=renderToStaticMarkup(React.createElement(ListingPricingForm,{listing:{id:"11111111-1111-4111-8111-111111111111",name:"Parcel A",weeklyLinden:1000,setupLinden:100,stripeWeeklyMinor:1234,stripeSetupMinor:250,published:true}}));expect(html).toContain("Edit Parcel A");expect(html).not.toContain("Weekly USD");});
 it("renders a scannable listing collection with explicit edit and modal create triggers",()=>{const html=renderToStaticMarkup(React.createElement(ListingsManager,{listings:[{id:"a",name:"Parcel A",kind:"PARCEL",published:true,weeklyLinden:1000,setupLinden:100,stripeWeeklyMinor:1234,stripeSetupMinor:250,stripeCurrency:"usd"}]}));expect(html).toContain("New property listing");expect(html).toContain("Edit Parcel A");expect(html).toContain("$12.34");expect(html).toContain('class="publication-state published"');expect(html).not.toContain("Add property listing");});
 it("styles publishing state as unboxed green text and reserves modal title space",()=>{const css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8");expect(css).toMatch(/\.publication-state\.published\{[^}]*color:#[0-9a-f]+[^}]*background:none/);expect(css).toMatch(/\.modal-header>div\{[^}]*min-width:0[^}]*padding-right/);});
 it("keeps worker health compact and colors healthy text green",()=>{const css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8");expect(css).toMatch(/\.worker-health\{[^}]*padding:/);expect(css).toMatch(/\.health-state\.healthy\{[^}]*color:#[0-9a-f]+/);});
 it("renders an accessible titled modal surface",()=>{const html=renderToStaticMarkup(React.createElement(Modal,{open:true,onClose:()=>undefined,title:"Edit listing",description:"Update customer-facing prices."},React.createElement("button",null,"Save")));expect(html).toContain('role="dialog"');expect(html).toContain('aria-modal="true"');expect(html).toContain("Edit listing");expect(html).toContain("Update customer-facing prices.");});
 it("renders an accessible terminal listing rebind control",()=>{const html=renderToStaticMarkup(React.createElement(TerminalActions,{id:"terminal",listingId:"a",listings:[{id:"a",name:"Parcel A"},{id:"b",name:"Parcel B"}]}));expect(html).toContain("Rebind terminal to listing");expect(html).toContain("Parcel B");expect(html).toContain("Rebind");});
 it("does not ask operators for a configurable grid",()=>{const html=renderToStaticMarkup(React.createElement(TerminalProvisionForm,{listings:[{id:"a",name:"Parcel A"}]}));expect(html).not.toContain("Grid");expect(html).not.toContain('name="shard"');});
 it("renders recovery controls only for actionable provider states",()=>{const failed=renderToStaticMarkup(React.createElement(ProviderRecoveryAction,{id:"a",state:"FAILED"}));const queued=renderToStaticMarkup(React.createElement(ProviderRecoveryAction,{id:"b",state:"QUEUED"}));expect(failed).toContain("Retry");expect(failed).toContain("Resolve");expect(queued).toContain("In progress");expect(queued).not.toContain("Retry");});
 it("uses accessible form surfaces instead of browser prompt dialogs",()=>{for(const file of ["admin-ops.tsx","rental-controls.tsx","reservation-actions.tsx","user-role-form.tsx"]){const source=readFileSync(new URL(`../components/${file}`,import.meta.url),"utf8");expect(source).not.toMatch(/\bprompt\(|\bconfirm\(|\balert\(/);}});
 it("keeps terminal health controls and owner identity visible without callback URLs",()=>{const page=readFileSync(new URL("../app/management/terminals/page.tsx",import.meta.url),"utf8");expect(page).toContain("si.avatar_id");expect(page).toContain("TerminalHealthAction");expect(page).not.toContain("Callback URL");expect(page).not.toContain("callback_url");});
 it("filters simulation workers from the service health query",()=>{const page=readFileSync(new URL("../app/management/audit/page.tsx",import.meta.url),"utf8");expect(page).toContain("mode NOT IN ('simulation','SIMULATION')");expect(page).toContain("callback backlog");});
});
