import React from "react";import{renderToStaticMarkup}from"react-dom/server";import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";import{ListingPricingForm,ListingsManager}from"../components/inventory-form.js";import{Modal}from"../components/form-primitives.js";import{TerminalActions,TerminalProvisionForm}from"../components/admin-ops.js";import{ProviderRecoveryAction}from"../components/provider-recovery-action.js";
const source=(file:string)=>readFileSync(new URL(file,import.meta.url),"utf8");
describe("Control Room management controls",()=>{
 it("renders decimal currency pricing editors with accessible labels",()=>{const html=renderToStaticMarkup(React.createElement(ListingPricingForm,{listing:{id:"11111111-1111-4111-8111-111111111111",name:"Parcel A",weeklyLinden:1000,setupLinden:100,stripeWeeklyMinor:1234,stripeSetupMinor:250,published:true}}));expect(html).toContain("Edit Parcel A");expect(html).not.toContain("Weekly USD");});
 it("renders a scannable listing collection with explicit edit and modal create triggers",()=>{const html=renderToStaticMarkup(React.createElement(ListingsManager,{listings:[{id:"a",name:"Parcel A",kind:"PARCEL",published:true,weeklyLinden:1000,setupLinden:100,stripeWeeklyMinor:1234,stripeSetupMinor:250,stripeCurrency:"usd"}]}));expect(html).toContain("New property listing");expect(html).toContain("Edit Parcel A");expect(html).toContain("$12.34");expect(html).toContain('class="publication-state published"');expect(html).not.toContain("Add property listing");});
 it("styles publishing state as unboxed green text and reserves modal title space",()=>{const css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8");expect(css).toMatch(/\.publication-state\.published\{[^}]*color:#[0-9a-f]+[^}]*background:none/);expect(css).toMatch(/\.modal-header>div\{[^}]*min-width:0[^}]*padding-right/);});
 it("keeps worker health compact and colors healthy text green",()=>{const css=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8");expect(css).toMatch(/\.worker-health\{[^}]*padding:/);expect(css).toMatch(/\.health-state\.healthy\{[^}]*color:#[0-9a-f]+/);});
 it("renders an accessible titled modal surface",()=>{const html=renderToStaticMarkup(React.createElement(Modal,{open:true,onClose:()=>undefined,title:"Edit listing",description:"Update customer-facing prices."},React.createElement("button",null,"Save")));expect(html).toContain('role="dialog"');expect(html).toContain('aria-modal="true"');expect(html).toContain("Edit listing");expect(html).toContain("Update customer-facing prices.");});
 it("renders an accessible terminal listing rebind control",()=>{const html=renderToStaticMarkup(React.createElement(TerminalActions,{id:"terminal",listingId:"a",listings:[{id:"a",name:"Parcel A"},{id:"b",name:"Parcel B"}]}));expect(html).toContain("Rebind terminal to listing");expect(html).toContain("Parcel B");expect(html).toContain("Rebind");});
 it("does not ask operators for a configurable grid",()=>{const html=renderToStaticMarkup(React.createElement(TerminalProvisionForm,{listings:[{id:"a",name:"Parcel A"}]}));expect(html).not.toContain("Grid");expect(html).not.toContain('name="shard"');});
 it("renders recovery controls only for actionable provider states",()=>{const failed=renderToStaticMarkup(React.createElement(ProviderRecoveryAction,{id:"a",state:"FAILED"}));const queued=renderToStaticMarkup(React.createElement(ProviderRecoveryAction,{id:"b",state:"QUEUED"}));expect(failed).toContain("Retry");expect(failed).toContain("Resolve");expect(queued).toContain("In progress");expect(queued).not.toContain("Retry");});
 it("uses accessible form surfaces instead of browser prompt dialogs",()=>{for(const file of ["admin-ops.tsx","rental-controls.tsx","reservation-actions.tsx","user-role-form.tsx"]){const source=readFileSync(new URL(`../components/${file}`,import.meta.url),"utf8");expect(source).not.toMatch(/\bprompt\(|\bconfirm\(|\balert\(/);}});
 it("shows only owner names and deletes revoked terminal bindings", () => {
   const page = readFileSync(new URL("../app/management/terminals/page.tsx", import.meta.url), "utf8");
   const route = readFileSync(new URL("../app/api/admin/terminals/[id]/route.ts", import.meta.url), "utf8");
   expect(page).toContain("u.display_name owner_name");
   expect(page).not.toContain("<small className=\"mono\">{t.owner_id}</small>");
   expect(page).toContain("WHERE t.enabled");
   expect(route).toContain("DELETE FROM terminals");
   expect(readFileSync(new URL("../../../../packages/db/migrations/015_terminal_revocation_delete.sql", import.meta.url), "utf8")).toContain("DELETE FROM terminals WHERE enabled = false");
 });

 it("filters simulation workers from the service health query",()=>{const page=readFileSync(new URL("../app/management/audit/page.tsx",import.meta.url),"utf8");expect(page).toContain("mode NOT IN ('simulation','SIMULATION')");expect(page).toContain("callback backlog");});
 it("declares a device-width viewport for mobile navigation",()=>{const layout=readFileSync(new URL("../app/layout.tsx",import.meta.url),"utf8");expect(layout).toContain("viewport:Viewport={width:\"device-width\",initialScale:1}");});
 it("loads Bootstrap 5.3.8 and uses its shared responsive primitives",()=>{const pkg=JSON.parse(source("../../package.json"));const css=source("../app/globals.css");const shell=source("../components/app-shell.tsx");expect(pkg.dependencies.bootstrap).toBe("5.3.8");expect(css).toContain('@import "bootstrap/dist/css/bootstrap.min.css"');expect(shell).toContain("d-md-none");expect(shell).toContain("nav-link");expect(shell).toContain("btn-outline-light");expect(css).toContain(".form-control,.form-select");expect(css).toContain(".modal-backdrop .modal-dialog");});
 it("renders Bootstrap form and modal classes without removing accessible semantics",()=>{const html=renderToStaticMarkup(React.createElement(Modal,{open:true,onClose:()=>undefined,title:"Edit listing"},React.createElement("input",{className:"form-control","aria-label":"Name"})));expect(html).toContain("modal-dialog");expect(html).toContain("modal-content");expect(html).toContain("btn-close");expect(html).toContain("form-control");expect(html).toContain('aria-modal="true"');});

});
